language: perl
perl:
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "cpanm Dist::Zilla"
  - "cpanm Dist::Zilla::Plugin::MakeMaker::Awesome"
  - "cpanm Pod::Weaver::Plugin::Encoding"
  - "cpanm Pod::Weaver::Plugin::StopWords"
  - "cpanm Pod::Weaver::Section::Support"
  - "git config --global github.user mjgardner"
  - "git clone git://github.com/mjgardner/mousex-getopt.git ../mousex-getopt"
  - "pushd ../mousex-getopt"
  - "dzil authordeps | xargs cpanm"
  - "dzil build --in mousex-getopt"
  - "cd mousex-getopt"
  - "cpanm ."
  - "popd"
install: "dzil authordeps | xargs cpanm && dzil listdeps | xargs cpanm --verbose"
script: "dzil test --release"
